### ISSUE TITLE
Return type here is MessageOrPromptOrError

### ISSUE THREAD

**Issue by KodeSaiRatnakar** [ZeroNetX/zeronet_ws#4]
https://github.com/ZeroNetX/zeronet_ws/blob/7e92bb4305e7cd9fb944600a6b29fc892449ef21/lib/extensions/plugins/optional.dart#L36

**Comment by canewsin** [comment]
Fixed in https://github.com/ZeroNetX/zeronet_ws/commit/c071687b813758b136f7c97246a33938ef33c292
